# This is a production docker file, paths are relative to the project root

FROM php:7.2-fpm-alpine

RUN apk --no-cache add icu

RUN \
    apk --no-cache add icu-dev && \
    docker-php-ext-install intl && \
    apk del icu-dev

COPY app                    /var/www/html/app
COPY vendor                 /var/www/html/vendor
COPY public                 /var/www/html/public
